platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine/git
    tag: latest

inputs:
- name: terraform
- name: source

params:
  github_token: ((github_token))

run:
  path: source/concourse/tasks/add-state-to-git/task.sh
