platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine/git
    tag: latest

inputs:
- name: terraform

run:
  path: source/concourse/tasks/add-stage-to-git/terraform.sh
