platform: linux

image_resource:
  type: docker-image
  source:
    repository: hashicorp/terraform
    tag: "0.11.8"

inputs:
- name: source

outputs:
- name: terraform

caches:
- path: terraform-cache

run:
  path: source/concourse/tasks/terraform/terraform.sh
